export const SET_CART = 'SET_CART'
export const SET_ITEM = 'SET_ITEM'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const REMOVE_ONE_ITEM = 'REMOVE_ONE_ITEM'
export const REMOVE_ALL = 'REMOVE_ALL'